---
- repo: https://github.com/adrienverge/yamllint.git
  sha: v1.10.0
  hooks:
    - id: yamllint

- repo: https://github.com/ansible/ansible-lint.git
  sha: v4.1.0
  hooks:
  - id: ansible-lint
    files: \.(yaml|yml)$

- repo: https://github.com/willthames/ansible-review.git
  sha: v0.13.9
  hooks:
  - id: ansible-review
    files: \.(yaml|yml)$
...
