---
- name: Setup pre-requisite python packages
  when: install_dependencies | bool
  package:
    name: "{{ yum_dependencies }}"
    state: present

- name: Setup pre-requisite pip packages
  when: install_dependencies | bool
  pip:
    name: "{{ pip_dependencies }}"
    state: present

- name: Copy requirements.txt to target for FTL virtualenv
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: "Create virtualenv {{ virtual_env_name }} for FTL"
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: "{{ virtual_env_home }}/{{ virtual_env_name }}"
    virtualenv_site_packages: no
...
