---
- name: Setup pre-requisite python packages
  package:
    name: "{{ yum_dependencies }}"
    state: present

- name: Setup pre-requisite pip packages
  pip:
    name: "{{ pip_dependencies }}"
    state: present

- name: Copy requirements.txt to target for FTL virtualenv
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: "Create virtualenv {{ virtual_env_name }} for FTL"
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: "{{ virtual_env_home }}/{{ virtual_env_name }}"
    virtualenv_site_packages: no

- name: Setup selinux bindings within virtualenv to allow report writing
  file:
    src: /usr/lib64/python2.7/site-packages/selinux/
    dest: "{{ virtual_env_home }}/{{ virtual_env_name }}/lib/python2.7/site-packages/selinux"
    state: link
...
