---
- name: Setup pre-requisite python packages
  when: install_dependencies | bool
  block:
    - name: For python2
      package:
        name: "{{ yum_dependencies }}"
        state: present
      when: not use_python3

    - name: For python3
      package:
        name: "{{ yum_dependencies_python3 }}"
        state: present
      when: use_python3

- name: Setup pre-requisite pip packages
  when: install_dependencies | bool
  pip:
    name: "{{ pip_dependencies }}"
    state: present

- name: Copy requirements.txt to target for FTL virtualenv
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: "Create virtualenv {{ virtual_env_name }} for FTL"
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: "{{ virtual_env_home }}/{{ virtual_env_name }}"
    virtualenv_site_packages: no
...
