---
  # Setup the FTL virtualenv on grader host
- include_tasks: setup-virtualenv.yml

  # Insert the FTL git repo on grader host
- include_tasks: insert-ftl-repo.yml

  # Create local facts from student and course metadata
- include_tasks: create-local-facts.yml

  # Insert the wrapper scripts called by students
- include_tasks: insert-wrapper-scripts.yml
...
