---
# Create the FTL virtualenv on grader host
- import_tasks: create-virtualenv.yml

# Insert the FTL git repo on grader host
- import_tasks: insert-ftl-repo.yml

# Create local facts from student and course metadata
- import_tasks: create-local-facts.yml

# Insert the wrapper scripts called by students
- import_tasks: insert-wrapper-scripts.yml
...
