---
- name: Setup pre-requisite python packages
  yum:
    name: "{{ python_dependencies }}"
    state: present

- name: Setup pre-requisite pip packages
  pip:
    name: "{{ pip_dependencies }}"
    state: present

- name: Copy requirements.txt to target for FTL virtualenv
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: "Create virtualenv {{ virtual_env_name }} for FTL"
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: "{{ virtual_env_home }}/{{ virtual_env_name }}"
    virtualenv_site_packages: true
...
