#!/usr/bin/env bash

PURPOSE=$(basename $0)

if [ $# -ne 3 ];
then  
  echo "Usage: ${PURPOSE} course-name lab-number student-id"
  echo
  echo "lab-number in format 03_01"
  exit 1
fi  

COURSE_NAME=$1
LAB_NUMBER=$2
STUDENT_ID=$3

# wrapper script for grading playbook for lab

VIRTUALENV=/opt/virtualenvs/venv-grading

# You can set the FTL_REPO_HOME var in your environment to point
# to the repo you are developing in
if [ -z "$FTL_REPO_HOME" ]
then
    FTL_REPO_HOME=/opt/ftl-repo-clone/
fi

GRADE_REPORT=/tmp/grading_report.txt
export LOG_FILE=/tmp/opentlc_ansible.log

# Clean up - next bit is a job for ansible

if [ -f ${GRADE_REPORT} ]; 
then
  cp  ${GRADE_REPORT} ${GRADE_REPORT}-previous
fi

# Make sure ansible finds the correct roles if it loads a new ansible.cfg

export ANSIBLE_ROLES_PATH=${FTL_REPO_HOME}/roles:${FTL_REPO_HOME}/roles-ftl-runtime
export FILE=${FTL_REPO_HOME}/courses/${COURSE_NAME}/ansible.cfg

if [ -f $FILE ]; then
   export ANSIBLE_CONFIG=${FILE}
fi

# Activate a protected vurtualenv with all dependencies and it's own ansible

echo "Starting ${PURPOSE} Process"

source ${VIRTUALENV}/bin/activate

( cd ${FTL_REPO_HOME};  ansible-playbook main.yml         \
  -e @vars/global_vars.yml                                \
  -e course_name=${COURSE_NAME}                           \
  -e purpose=${PURPOSE}                                   \
  -e lab_number=${LAB_NUMBER}                             \
  -e student_id=${STUDENT_ID}    > ${LOG_FILE} 2>&1 )

if [ $? -ne 0 ]
then
  echo ${PURPOSE} ERROR: Failed to run sucessfully
  echo "Grading Log (ansible): ${LOG_FILE}"
fi

# Output the error report

echo "Finished ${PURPOSE} Process"
echo

if [ ${PURPOSE} == "grade_lab" ] 
then  
  cat ${GRADE_REPORT}

  echo
  echo "Grading Report:        ${GRADE_REPORT}"
  echo "Grading Log (ansible): ${LOG_FILE}"
fi 
if [ ${PURPOSE} == "solve_lab" ] 
then  
  echo "Solver has completed lab"
fi 
if [ ${PURPOSE} == "reset_lab" ] 
then  
  echo "Lab has been reset to starting point"
fi 
